# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

abstract_target 'Gardener' do
    use_frameworks!
    pod 'SwiftLint'
    pod 'Booster'
    
    target 'tree' do
    end
    target 'Trend' do
    end
    target 'TrendUI' do
    end
    target 'NetworkFetcher' do
    end
end
